### ISSUE TITLE
cli create error `TypeError: Cannot read properties of undefined (reading 'apply')`

### ISSUE THREAD

**Issue by SmallTeddy** [Ting-Code/Ting-Library-Monorepo#7]
pnpm version: 9.9.0
node version : 18.16.0

run pnpm create tingcli
select monorepo
imput project name

<img width="1125" alt="image" src="https://github.com/user-attachments/assets/6e9f3495-0754-4f5b-af39-da2791a8e53f">

**Comment by Ting-Code** [comment]
[a0312ca](https://github.com/Ting-Code/Ting-Library-Monorepo/commit/a0312caf80cb055b824642242801c4480c20f5f6)已修复改问题，感谢反馈
